Repository pinkywafer/Anniversaries, pull requests merged in 2021-02, with the labels that each got.

#93 Fix error in years attributes calculation
  custom_components/anniversaries/sensor.py
Labels: bug, patch

#91 Fix french translation
  custom_components/anniversaries/translations/fr.json
Labels: bugfix, patch

#94 update release action
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: Update, minor

#95 update release drafter
  .github/release-drafter.yml
Labels: Update, minor

#97 Add versions for requirements
  custom_components/anniversaries/manifest.json
Labels: bugfix, patch

#98 Adds Estonian translation
  custom_components/anniversaries/translations/et.json
Labels: enhancement, minor
